### ISSUE TITLE
Interfaz en español?

### ISSUE THREAD

**Issue by paocorrales** [yabellini/tutorialgRaficosFN#3]
Yani, aprovechando que ahora {learnr} tiene interfaz en español se podría usar en este tutorial. Es implica cambiar algo del texto cuando menciona los botones en inglés. 

¿Qué te parece? Puedo hacer un PR si me decís que cambiar en el YAML :D

**Comment by yabellini** [comment]
Si, con la ultima versión de learnr (hay que instalar la version de desarrollo): 

```
output: 
  learnr::tutorial:
    language: es
```

**Comment by paocorrales** [comment]
Un rato después lo encontré! Ahí fue PR

**Comment by yabellini** [comment]
Gracias por las mejoras!
