### ISSUE TITLE
Agergar dependencias en DESCRIPTION

### ISSUE THREAD

**Issue by eliocamp** [yabellini/tutorialgRaficosFN#5]
Les di este tutorial como ejercicio para mis estudiantes pero se están encontrando con el problema de que requiere paquetes que no tienen instalados, como visNetwork. ¿Esos no deberían instalarse automáticamente como dependencias cuando se instala este paquete? 

Saludos!

**Comment by yabellini** [comment]
Si! Voy a chequear bien! Gracias

**Comment by yabellini** [comment]
Agregué los paquetes necesarios para el tutorial.  Gracias por avisar :-)
